eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 2
      #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
      #org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean.leaseExpirationDurationInSeconds
      leaseExpirationDurationInSeconds: 6
server:
  port: 8762
spring:
  application:
    name: service-hi
